app:
  eureka-server: localhost
server:
  port: 8000

spring:
  application:
    name: apiGateWay
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: discoveryServer
              uri: http://localhost:8761/
              predicates:
                - Path=/eureka/web
              filters:
                - SetPath=/
            - id: discoveryServer-static
              uri: http://localhost:8761/
              predicates:
                - Path=/eureka/**
            - id: course-service
              uri: lb://course-service
              predicates:
                - Path=/course/**
              filters:
                - name: CircuitBreaker
                  args:
                    id: course-service
                    fallbackUri: forward:/fallback/course
            - id: student-service
              uri: lb://student-service
              predicates:
                - Path=/student/**
              filters:
                - name: CircuitBreaker
                  args:
                    id: student-service
                    fallbackUri: forward:/fallback/student
resilience4j:
  circuitbreaker:
    instances:
      student-service:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
      course-service:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/