server.port: 0
base:
  url: http://localhost:8000/
spring:
  application:
    name: student-service
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5435/student
    username: jaga
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 10
        ringBufferSizeInHalfOpenState: 5
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
  retry:
    instances:
      backendA:
        maxAttempts: 3
        waitDuration: 5000